// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: support_message.
// - Entity ID: 102019a333c492f7e6f86edd32ab61d1f59.
// - Entity Version: 102019b2203e15f7947b569d09de7bc8fb5.
// - Task ID: 694000cc4f4905925fbc16f7.
// - Task Root ID: 6902507d3f4d1733d49dcb09.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for SupportMessageSender
 */
export enum SupportMessageSender {
  Unspecified = 0,
  User = 1,
  Agent = 2,
}



/**
 * Interface for SupportMessageModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface SupportMessageModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  conversation_id: string;
  sender: SupportMessageSender;
  content: string;
}

/**
 * ORM class for SupportMessage entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class SupportMessageORM {
  private static instance: SupportMessageORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019a333c492f7e6f86edd32ab61d1f59';
    this.entityName = 'support_message';
    this.entityVersion = '102019b2203e15f7947b569d09de7bc8fb5';
    this.taskId = '694000cc4f4905925fbc16f7';
    this.taskRootId = '6902507d3f4d1733d49dcb09';
  }

  /**
   * Get singleton instance of SupportMessageORM
   */
  public static getInstance(): SupportMessageORM {
    if (!SupportMessageORM.instance) {
      SupportMessageORM.instance = new SupportMessageORM();
    }
    
    return SupportMessageORM.instance;
  }

  /**
   * Get all SupportMessage records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllSupportMessage(): Promise<SupportMessageModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new SupportMessage record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertSupportMessage(data: SupportMessageModel[]): Promise<SupportMessageModel[]> {
    const structured = data.map((item) => CreateData(SupportMessageModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all SupportMessage records
   */
  async purgeAllSupportMessage(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List SupportMessage records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listSupportMessage(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[SupportMessageModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get support_message by Id index
   * This function gets data by index.
   */
  async getSupportMessageById(
    id: string,
  ): Promise<SupportMessageModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) support_message by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSupportMessageById(
    id: string,
    data: SupportMessageModel
  ): Promise<SupportMessageModel[]> {
    const index = createIndexId(
      id
    );

    const values = SupportMessageModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete support_message by Id index
   */
  async deleteSupportMessageById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get support_message by DataCreator index
   * This function gets data by index.
   */
  async getSupportMessageByDataCreator(
    data_creator: string,
  ): Promise<SupportMessageModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) support_message by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSupportMessageByDataCreator(
    data_creator: string,
    data: SupportMessageModel
  ): Promise<SupportMessageModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = SupportMessageModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete support_message by DataCreator index
   */
  async deleteSupportMessageByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get support_message by DataUpdater index
   * This function gets data by index.
   */
  async getSupportMessageByDataUpdater(
    data_updater: string,
  ): Promise<SupportMessageModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) support_message by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSupportMessageByDataUpdater(
    data_updater: string,
    data: SupportMessageModel
  ): Promise<SupportMessageModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = SupportMessageModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete support_message by DataUpdater index
   */
  async deleteSupportMessageByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get support_message by ConversationId index
   * This function gets data by index.
   */
  async getSupportMessageByConversationId(
    conversation_id: string,
  ): Promise<SupportMessageModel[]> {
    const index = createIndexConversationId(
      conversation_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) support_message by ConversationId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSupportMessageByConversationId(
    conversation_id: string,
    data: SupportMessageModel
  ): Promise<SupportMessageModel[]> {
    const index = createIndexConversationId(
      conversation_id
    );

    const values = SupportMessageModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete support_message by ConversationId index
   */
  async deleteSupportMessageByConversationId(
    conversation_id: string
  ): Promise<void> {
    const index = createIndexConversationId(
      conversation_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to SupportMessageModel data array
   */
  private resultToData(values: Data[]): SupportMessageModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return SupportMessageModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as SupportMessageModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized SupportMessageModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is SupportMessageModel => item !== null);
  }
}

/**
 * Convert SupportMessageModel data to Value array
 */
function SupportMessageModelToValues(data: SupportMessageModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'conversation_id', type: DataType.string, defaultValue: '' },
    { key: 'sender', type: DataType.enumeration, defaultValue: 0 },
    { key: 'content', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof SupportMessageModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to SupportMessageModel data
 */
function SupportMessageModelFromValues(values: Value[]): SupportMessageModel {
  const data: Partial<SupportMessageModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'conversation_id':
        data.conversation_id = ParseValue(value, DataType.string) as string;
        break;
      case 'sender':
        data.sender = ParseValue(value, DataType.enumeration) as SupportMessageSender;
        break;
      case 'content':
        data.content = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as SupportMessageModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for ConversationId fields
 */
function createIndexConversationId(
  conversation_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, conversation_id, 'conversation_id'),
  ];

  return {
    fields: ['conversation_id'],
    values
  };
}

export default SupportMessageORM;