// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: consultation.
// - Entity ID: 102019a338d9f5d7535818c6a82ba51c4c9.
// - Entity Version: 102019b2203e15f7947b569d09de7bc8fb5.
// - Task ID: 694000cc4f4905925fbc16f7.
// - Task Root ID: 6902507d3f4d1733d49dcb09.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for ConsultationStatus
 */
export enum ConsultationStatus {
  Unspecified = 0,
  PENDING = 1,
  COMPLETED = 2,
  VIEWED = 3,
}



/**
 * Interface for ConsultationModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface ConsultationModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_name: string;
  name: string;
  phone: string;
  address?: string | null;
  cep?: string | null;
  country?: string | null;
  city?: string | null;
  neighborhood?: string | null;
  status: ConsultationStatus;
  report_data?: string | null;
}

/**
 * ORM class for Consultation entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class ConsultationORM {
  private static instance: ConsultationORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019a338d9f5d7535818c6a82ba51c4c9';
    this.entityName = 'consultation';
    this.entityVersion = '102019b2203e15f7947b569d09de7bc8fb5';
    this.taskId = '694000cc4f4905925fbc16f7';
    this.taskRootId = '6902507d3f4d1733d49dcb09';
  }

  /**
   * Get singleton instance of ConsultationORM
   */
  public static getInstance(): ConsultationORM {
    if (!ConsultationORM.instance) {
      ConsultationORM.instance = new ConsultationORM();
    }
    
    return ConsultationORM.instance;
  }

  /**
   * Get all Consultation records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllConsultation(): Promise<ConsultationModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Consultation record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertConsultation(data: ConsultationModel[]): Promise<ConsultationModel[]> {
    const structured = data.map((item) => CreateData(ConsultationModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Consultation records
   */
  async purgeAllConsultation(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Consultation records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listConsultation(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[ConsultationModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get consultation by Id index
   * This function gets data by index.
   */
  async getConsultationById(
    id: string,
  ): Promise<ConsultationModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) consultation by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setConsultationById(
    id: string,
    data: ConsultationModel
  ): Promise<ConsultationModel[]> {
    const index = createIndexId(
      id
    );

    const values = ConsultationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete consultation by Id index
   */
  async deleteConsultationById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get consultation by DataCreator index
   * This function gets data by index.
   */
  async getConsultationByDataCreator(
    data_creator: string,
  ): Promise<ConsultationModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) consultation by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setConsultationByDataCreator(
    data_creator: string,
    data: ConsultationModel
  ): Promise<ConsultationModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = ConsultationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete consultation by DataCreator index
   */
  async deleteConsultationByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get consultation by DataUpdater index
   * This function gets data by index.
   */
  async getConsultationByDataUpdater(
    data_updater: string,
  ): Promise<ConsultationModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) consultation by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setConsultationByDataUpdater(
    data_updater: string,
    data: ConsultationModel
  ): Promise<ConsultationModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = ConsultationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete consultation by DataUpdater index
   */
  async deleteConsultationByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get consultation by CreateTimeDataCreator index
   * This function gets data by index.
   */
  async getConsultationByCreateTimeDataCreator(
    create_time: string,
    data_creator: string,
  ): Promise<ConsultationModel[]> {
    const index = createIndexCreateTimeDataCreator(
      create_time,
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) consultation by CreateTimeDataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setConsultationByCreateTimeDataCreator(
    create_time: string,
    data_creator: string,
    data: ConsultationModel
  ): Promise<ConsultationModel[]> {
    const index = createIndexCreateTimeDataCreator(
      create_time,
      data_creator
    );

    const values = ConsultationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete consultation by CreateTimeDataCreator index
   */
  async deleteConsultationByCreateTimeDataCreator(
    create_time: string,
    data_creator: string
  ): Promise<void> {
    const index = createIndexCreateTimeDataCreator(
      create_time,
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get consultation by DataCreatorStatus index
   * This function gets data by index.
   */
  async getConsultationByDataCreatorStatus(
    data_creator: string,
    status: ConsultationStatus,
  ): Promise<ConsultationModel[]> {
    const index = createIndexDataCreatorStatus(
      data_creator,
      status
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) consultation by DataCreatorStatus index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setConsultationByDataCreatorStatus(
    data_creator: string,
    status: ConsultationStatus,
    data: ConsultationModel
  ): Promise<ConsultationModel[]> {
    const index = createIndexDataCreatorStatus(
      data_creator,
      status
    );

    const values = ConsultationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete consultation by DataCreatorStatus index
   */
  async deleteConsultationByDataCreatorStatus(
    data_creator: string,
    status: ConsultationStatus
  ): Promise<void> {
    const index = createIndexDataCreatorStatus(
      data_creator,
      status
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to ConsultationModel data array
   */
  private resultToData(values: Data[]): ConsultationModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return ConsultationModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as ConsultationModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized ConsultationModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is ConsultationModel => item !== null);
  }
}

/**
 * Convert ConsultationModel data to Value array
 */
function ConsultationModelToValues(data: ConsultationModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_name', type: DataType.string, defaultValue: '' },
    { key: 'name', type: DataType.string, defaultValue: '' },
    { key: 'phone', type: DataType.string, defaultValue: '' },
    { key: 'address', type: DataType.string, defaultValue: null },
    { key: 'cep', type: DataType.string, defaultValue: null },
    { key: 'country', type: DataType.string, defaultValue: null },
    { key: 'city', type: DataType.string, defaultValue: null },
    { key: 'neighborhood', type: DataType.string, defaultValue: null },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
    { key: 'report_data', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof ConsultationModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to ConsultationModel data
 */
function ConsultationModelFromValues(values: Value[]): ConsultationModel {
  const data: Partial<ConsultationModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_name':
        data.user_name = ParseValue(value, DataType.string) as string;
        break;
      case 'name':
        data.name = ParseValue(value, DataType.string) as string;
        break;
      case 'phone':
        data.phone = ParseValue(value, DataType.string) as string;
        break;
      case 'address':
        data.address = ParseValue(value, DataType.string) as string | null;
        break;
      case 'cep':
        data.cep = ParseValue(value, DataType.string) as string | null;
        break;
      case 'country':
        data.country = ParseValue(value, DataType.string) as string | null;
        break;
      case 'city':
        data.city = ParseValue(value, DataType.string) as string | null;
        break;
      case 'neighborhood':
        data.neighborhood = ParseValue(value, DataType.string) as string | null;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as ConsultationStatus;
        break;
      case 'report_data':
        data.report_data = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as ConsultationModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for CreateTimeDataCreator fields
 */
function createIndexCreateTimeDataCreator(
  create_time: string,
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, create_time, 'create_time'),
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['create_time', 'data_creator'],
    values
  };
}
/**
 * Create index for DataCreatorStatus fields
 */
function createIndexDataCreatorStatus(
  data_creator: string,
  status: ConsultationStatus
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
    CreateValue(DataType.enumeration, status, 'status'),
  ];

  return {
    fields: ['data_creator', 'status'],
    values
  };
}

export default ConsultationORM;