// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: whatsapp_consultation.
// - Entity ID: 102019a32c899d57649ada8a6eea33a198e.
// - Entity Version: 102019b2203e15f7947b569d09de7bc8fb5.
// - Task ID: 694000cc4f4905925fbc16f7.
// - Task Root ID: 6902507d3f4d1733d49dcb09.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for WhatsappConsultationStatus
 */
export enum WhatsappConsultationStatus {
  Unspecified = 0,
  Active = 1,
  Cancelled = 2,
  Completed = 3,
}



/**
 * Interface for WhatsappConsultationModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface WhatsappConsultationModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  name: string;
  email: string;
  phone: string;
  address?: string | null;
  cep?: string | null;
  country?: string | null;
  city?: string | null;
  neighborhood?: string | null;
  start_date: string;
  status: WhatsappConsultationStatus;
}

/**
 * ORM class for WhatsappConsultation entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class WhatsappConsultationORM {
  private static instance: WhatsappConsultationORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019a32c899d57649ada8a6eea33a198e';
    this.entityName = 'whatsapp_consultation';
    this.entityVersion = '102019b2203e15f7947b569d09de7bc8fb5';
    this.taskId = '694000cc4f4905925fbc16f7';
    this.taskRootId = '6902507d3f4d1733d49dcb09';
  }

  /**
   * Get singleton instance of WhatsappConsultationORM
   */
  public static getInstance(): WhatsappConsultationORM {
    if (!WhatsappConsultationORM.instance) {
      WhatsappConsultationORM.instance = new WhatsappConsultationORM();
    }
    
    return WhatsappConsultationORM.instance;
  }

  /**
   * Get all WhatsappConsultation records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllWhatsappConsultation(): Promise<WhatsappConsultationModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new WhatsappConsultation record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertWhatsappConsultation(data: WhatsappConsultationModel[]): Promise<WhatsappConsultationModel[]> {
    const structured = data.map((item) => CreateData(WhatsappConsultationModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all WhatsappConsultation records
   */
  async purgeAllWhatsappConsultation(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List WhatsappConsultation records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listWhatsappConsultation(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[WhatsappConsultationModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get whatsapp_consultation by Id index
   * This function gets data by index.
   */
  async getWhatsappConsultationById(
    id: string,
  ): Promise<WhatsappConsultationModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) whatsapp_consultation by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWhatsappConsultationById(
    id: string,
    data: WhatsappConsultationModel
  ): Promise<WhatsappConsultationModel[]> {
    const index = createIndexId(
      id
    );

    const values = WhatsappConsultationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete whatsapp_consultation by Id index
   */
  async deleteWhatsappConsultationById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get whatsapp_consultation by DataCreator index
   * This function gets data by index.
   */
  async getWhatsappConsultationByDataCreator(
    data_creator: string,
  ): Promise<WhatsappConsultationModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) whatsapp_consultation by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWhatsappConsultationByDataCreator(
    data_creator: string,
    data: WhatsappConsultationModel
  ): Promise<WhatsappConsultationModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = WhatsappConsultationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete whatsapp_consultation by DataCreator index
   */
  async deleteWhatsappConsultationByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get whatsapp_consultation by DataUpdater index
   * This function gets data by index.
   */
  async getWhatsappConsultationByDataUpdater(
    data_updater: string,
  ): Promise<WhatsappConsultationModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) whatsapp_consultation by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWhatsappConsultationByDataUpdater(
    data_updater: string,
    data: WhatsappConsultationModel
  ): Promise<WhatsappConsultationModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = WhatsappConsultationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete whatsapp_consultation by DataUpdater index
   */
  async deleteWhatsappConsultationByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get whatsapp_consultation by DataCreatorStatus index
   * This function gets data by index.
   */
  async getWhatsappConsultationByDataCreatorStatus(
    data_creator: string,
    status: WhatsappConsultationStatus,
  ): Promise<WhatsappConsultationModel[]> {
    const index = createIndexDataCreatorStatus(
      data_creator,
      status
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) whatsapp_consultation by DataCreatorStatus index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWhatsappConsultationByDataCreatorStatus(
    data_creator: string,
    status: WhatsappConsultationStatus,
    data: WhatsappConsultationModel
  ): Promise<WhatsappConsultationModel[]> {
    const index = createIndexDataCreatorStatus(
      data_creator,
      status
    );

    const values = WhatsappConsultationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete whatsapp_consultation by DataCreatorStatus index
   */
  async deleteWhatsappConsultationByDataCreatorStatus(
    data_creator: string,
    status: WhatsappConsultationStatus
  ): Promise<void> {
    const index = createIndexDataCreatorStatus(
      data_creator,
      status
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to WhatsappConsultationModel data array
   */
  private resultToData(values: Data[]): WhatsappConsultationModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return WhatsappConsultationModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as WhatsappConsultationModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized WhatsappConsultationModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is WhatsappConsultationModel => item !== null);
  }
}

/**
 * Convert WhatsappConsultationModel data to Value array
 */
function WhatsappConsultationModelToValues(data: WhatsappConsultationModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'name', type: DataType.string, defaultValue: '' },
    { key: 'email', type: DataType.string, defaultValue: '' },
    { key: 'phone', type: DataType.string, defaultValue: '' },
    { key: 'address', type: DataType.string, defaultValue: null },
    { key: 'cep', type: DataType.string, defaultValue: null },
    { key: 'country', type: DataType.string, defaultValue: null },
    { key: 'city', type: DataType.string, defaultValue: null },
    { key: 'neighborhood', type: DataType.string, defaultValue: null },
    { key: 'start_date', type: DataType.string, defaultValue: '' },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof WhatsappConsultationModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to WhatsappConsultationModel data
 */
function WhatsappConsultationModelFromValues(values: Value[]): WhatsappConsultationModel {
  const data: Partial<WhatsappConsultationModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'name':
        data.name = ParseValue(value, DataType.string) as string;
        break;
      case 'email':
        data.email = ParseValue(value, DataType.string) as string;
        break;
      case 'phone':
        data.phone = ParseValue(value, DataType.string) as string;
        break;
      case 'address':
        data.address = ParseValue(value, DataType.string) as string | null;
        break;
      case 'cep':
        data.cep = ParseValue(value, DataType.string) as string | null;
        break;
      case 'country':
        data.country = ParseValue(value, DataType.string) as string | null;
        break;
      case 'city':
        data.city = ParseValue(value, DataType.string) as string | null;
        break;
      case 'neighborhood':
        data.neighborhood = ParseValue(value, DataType.string) as string | null;
        break;
      case 'start_date':
        data.start_date = ParseValue(value, DataType.string) as string;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as WhatsappConsultationStatus;
        break;
    }
  }
  
  return data as WhatsappConsultationModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for DataCreatorStatus fields
 */
function createIndexDataCreatorStatus(
  data_creator: string,
  status: WhatsappConsultationStatus
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
    CreateValue(DataType.enumeration, status, 'status'),
  ];

  return {
    fields: ['data_creator', 'status'],
    values
  };
}

export default WhatsappConsultationORM;